#include "LoadBalancer.h"
// Comments were generated by ChatGPT
/**
 * @brief Constructs a new load balancer with the given number of servers
 * @param serverCount The number of servers to create
 */
LoadBalancer::LoadBalancer (int serverCount) {
  for(int i = 0; i < serverCount; ++i) {
    servers.emplace_back();
  }
  clockTime = 0;
  serversDone = false;
}
/**
 * @brief Performs a single clock cycle for the load balancer
 *
 * This function iterates through all the servers and checks if any of them
 * have completed their current task. If a server is available, it will start
 * processing the next request in the queue. If no servers are available and
 * the request queue is empty, it sets the `serversDone` flag to true.
 */
void LoadBalancer::performCycle() {
  bool hasRunning = false;
  for(int i = 0; i < servers.size(); i++) {
    bool res = servers[i].iterate();
    if(res) {
      if(servers[i].timeLeft == 0) {
        cout << "Server " << i << " has completed a task in " << servers[i].currentRequest.time << " time" << endl;
      }
      if(!requests.empty()) {
        cout << "Server " << i << " has been assigned a new request from ";
        servers[i].startNewRequest(requests.front());
        cout << requests.front().in << " to " << requests.front().out << " that takes time " << requests.front().time << " to process" << endl;
        requests.pop();
        hasRunning = true;
      }
    } else {
      hasRunning = true;
    }
  }
  if(!hasRunning) {
    serversDone = true;
  }
  numActive=0;
  for(int i = 0; i < servers.size(); i++) {
    if(servers[i].timeLeft > 0) {
        numActive++;
    }
  }
}
/**
 * @brief Prints the time left for each server's current task
 */
void LoadBalancer::validator() {
  cout << "queue items remaining " << requests.size() << endl;
}
